DOMAIN = "jse_helmi"

CONF_EMAIL = "email"
CONF_PASSWORD = "password"
CONF_CUSTOMER_ID = "customer_id"
CONF_METERING_POINT_ID = "metering_point_id"
CONF_CUTOFF_HOUR = "cutoff_hour"
CONF_UPDATE_MINUTE = "update_minute"
CONF_STALE_HOURS = "stale_hours"

DEFAULT_UPDATE_INTERVAL_MINUTES = 60
DEFAULT_CUTOFF_HOUR = 5
DEFAULT_UPDATE_MINUTE = 10
DEFAULT_STALE_HOURS = 3
